sonar.projectKey=tdreyno_abac
sonar.projectName=he-said
sonar.organization=tdreyno
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.integration.test.ts
sonar.exclusions=**/*.test.ts,**/*.integration.test.ts,**/*.typecheck.ts,**/coverage/**,**/dist/**

sonar.typescript.tsconfigPaths=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/sonar.lcov.info
sonar.typescript.lcov.reportPaths=coverage/sonar.lcov.info
sonar.coverage.exclusions=src/**/*.typecheck.ts,src/**/examples/**
