export * as algebra from "./core/algebra"
export {
  and,
  or,
  not,
  implies,
  oneOf,
  atLeast,
  atMost,
  exactly,
  through,
  term,
  fact,
  factIsTrue,
  attr,
  relation,
  eq,
  ne,
  gt,
  ge,
  lt,
  le,
  isNull,
  isNotNull,
  ref,
  forAll,
  select,
  distinct,
  letRule,
  annotateRule,
  buildEvaluationProofDetails,
  getRuleAnnotations,
  sortRulesByPriorityAndKind,
  getTermInfo,
  withExclusions,
  evaluator,
  derives,
  given,
} from "./core/algebra"
export {
  createInMemoryAdapter,
  validateStratifiedNegation,
} from "./core/algebra-inmemory"
export {
  createPostgresAdapter,
  planPostgresRule,
} from "./core/algebra-postgres"
export type {
  Environment,
  EvaluationInput,
  EvaluationProofDetails,
  EvaluationProof,
  EvaluatorAdapter,
  EvaluatorInstance,
  OutcomeToken,
  Relation,
  RuleAnnotations,
  RuleBranchOutcome,
  RuleReferenceToken,
  Rule,
  SourceComparisonOperator,
  SourceOrdering,
  SourcePredicate,
  Term,
  Fact,
  TermInfo,
  AttributeAccessor,
  PredicateExpression,
  PredicateOperand,
  TermPredicate,
  UnaryPredicate,
} from "./core/algebra"
export type {
  InMemoryAdapterOptions,
  InMemoryRelationFacts,
  InMemoryRelationRow,
} from "./core/algebra-inmemory"
export type {
  PlannedPostgresRule,
  PostgresAdapterOptions,
  PostgresSourceComparisonOperator,
  PostgresSourceOrdering,
  PostgresSourcePredicate,
  PostgresEdgeRelationSource,
  PostgresJoinTableRelationSource,
  PostgresProofDiagnostic,
  PostgresQueryExecutor,
  PostgresQueryResult,
  PostgresRelationMapping,
  PostgresRelationSource,
  PostgresTermEncoder,
  PostgresTermEncoding,
  PostgresTermDomainSource,
} from "./core/algebra-postgres"
